backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: source/images/uploads
public_folder: /images/uploads

#publish_mode: editorial_workflow #optional, enables publishing workflow

collections:
  #yaml middleman data example
  - name: product
    label: Product
    format: yml
    extension: yml
    folder: data/products/
    create: true
    slug: '{{title}}'
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Image, name: image, widget: image, required: true}

  # case study article example
  - name: Case Study
    label: Case Study
    format: frontmatter
    extension: .html.md
    folder: source/case-studies/
    create: true
    slug: '{{url}}'
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: URL, name: url, widget: string, required: true}
      - {label: Download, name: download, widget: file, required: false}
      - {label: Image, name: image, widget: image, required: true}
      - {label: Body, name: body, widget: markdown}
      - {label: Stats, name: stats, widget: string, required: true}

#markdown middleman blog example
  - name: blog
    label: Blog
    folder: source/posts/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{title}}'
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Description, name: description, widget: string}
      - {label: Image, name: image, widget: image}
      - {label: Body, name: body, widget: markdown}

  - name: pages
    label: Pages
    files:
      - file: "data/pages/home.yml"
        label: Homepage
        name: home
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}
          - label: Story
            name: story
            widget: markdown

  - name: settings
    label: Settings
    files:
      - file: data/settings/navigation.yml
        label: Navigation
        name: navigation
        fields:
          - label: Navigation
            name: nav_items
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string}
      - file: data/settings/units.yml
        label: Units
        name: units
        fields:
          - label: Currency
            name: currency
            widget: select
            options: ['€', '$', '£']
            default: '€'

          - label: Weight
            name: weight
            widget: select
            options: ['kg', ' st', ' lb']
            default: 'kg'
